function res = triangles_intersect(a, b, c, x, y, z)
 % input:
 % a, b, c - vertices of the first triangle
 % x, y, z - vertices of the second triangle
 % output
 % boolean - are triangles intersect

 mid_1 = (a + b + c) / 3;
 mid_2 = (x + y + z) / 3;

 res = (segments_intersect(a, b, x, y) ...
    || segments_intersect(a, b, x, z) ...
    || segments_intersect(a, b, y, z) ...
    || segments_intersect(a, c, x, y) ...
    || segments_intersect(a, c, x, z) ...
    || segments_intersect(a, c, y, z) ...
    || segments_intersect(b, c, x, y) ...
    || segments_intersect(b, c, x, z) ...
    || segments_intersect(b, c, y, z)) ...
    || ...
    ~(segments_intersect(mid_1, mid_2, a, b) ...
    || segments_intersect(mid_1, mid_2, a, c) ...
    || segments_intersect(mid_1, mid_2, b, c)) ...
    || ...
    ~(segments_intersect(mid_1, mid_2, x, y) ...
    || segments_intersect(mid_1, mid_2, x, z) ...
    || segments_intersect(mid_1, mid_2, y, z));

    

end